Module 1: Welcome to Python & Environment Setup
Goal: Understand Python’s philosophy, why it’s popular, and run a first script.

Key Topics:

What is Python? (Interpreted, dynamically typed, high-level language)

Why Python? (Readable syntax, massive ecosystem for web, AI, data science)

Setting up an environment (VS Code, Jupyter Notebooks, or standard Python IDLE)

In [ ]:
# First Python Script
print("Hello, Python World!")

Module 2: Variables & Core Data Types
Goal: Learn how Python stores and manipulates basic data.

Key Topics:

Variables as dynamic labels (no explicit type declaration needed)

Primary primitive types: int, float, str, bool

Basic arithmetic and string formatting (f-strings)

In [ ]:
# Variable declarations
user_name = "Alex"      # String
age = 25               # Integer
height_meters = 1.75   # Float
is_enrolled = True     # Boolean

# String interpolation using f-strings
print(f"Student {user_name} is {age} years old and {height_meters}m tall.")

Module 3: Control Flow (Conditionals & Loops)
Goal: Direct code execution using logic and iteration.

Key Topics:

Indentation as block structure (standard: 4 spaces)

Branching with if, elif, and else

Loops: for (iterating over ranges/sequences) and while (condition-based execution)

In [ ]:
# Conditional Logic
score = 85

if score >= 90:
    grade = "A"
elif score >= 80:
    grade = "B"
else:
    grade = "C"

print(f"Final Grade: {grade}")

# Iteration with a For Loop
print("\nCountdown:")
for count in range(3, 0, -1):
    print(count)

Module 4: Data Structures
Goal: Store and organize collections of data using built-in containers.

Key Topics:

Lists: Ordered, mutable sequences [1, 2, 3]

Dictionaries: Key-value keymaps {"key": "value"}

Tuples: Ordered, immutable sequences (1, 2)

Sets: Unordered collections of unique items {1, 2, 3}

In [ ]:
# Lists
languages = ["Python", "JavaScript", "C++"]
languages.append("Go")

# Dictionaries
developer = {
    "name": "Jordan",
    "role": "Data Scientist",
    "experience_years": 3
}

print(f"Favorite language: {languages[0]}")
print(f"Developer Role: {developer['role']}")

Module 5: Functions & Reusability
Goal: Write clean, modular, and reusable code blocks.

Key Topics:

Defining functions with def

Parameters and default arguments

Return values vs. output printing

Variable scope (Local vs. Global)

In [ ]:
def calculate_total(price, tax_rate=0.08):
    """Calculates total cost including tax."""
    return price + (price * tax_rate)

# Function call
item_price = 100
total = calculate_total(item_price)
print(f"Total price with default tax: ${total:.2f}")

Module 6: Basic Error Handling & File Operations
Goal: Prevent program crashes and interact with external text files.

Key Topics:

Graceful failure using try / except blocks

Safe file interaction using context managers (with open(...))

In [ ]:
# Error Handling
try:
    result = 10 / 0
except ZeroDivisionError:
    print("Caught an error: Cannot divide by zero!")

# Writing and Reading Files
filename = "sample.txt"

# Write mode ('w')
with open(filename, "w") as file:
    file.write("Python handles file I/O cleanly.")

# Read mode ('r')
with open(filename, "r") as file:
    content = file.read()
    print(f"File Content: {content}")

NumPy (Numerical Python)
NumPy provides multi-dimensional array objects (ndarray) and vectorized operations, eliminating slow Python for loops.

Key Concepts

Vectorization: Performing batch operations on arrays without explicit loops.

Broadcasting: Rules for operations between arrays of different shapes.

Array Creation

np.array(): Converts lists or tuples into a NumPy ndarray.

np.zeros(), np.ones(): Generates arrays pre-filled with zeros or ones of a given shape.

np.arange(start, stop, step): Creates evenly spaced values within a given interval.

np.linspace(start, stop, num): Generates num evenly spaced numbers over a specified interval.

Shape & Manipulation

array.reshape(): Gives a new shape to an array without changing its data.

np.concatenate(), np.vstack(), np.hstack(): Joins a sequence of arrays along an existing or new axis.

array.flatten() / array.ravel(): Collapses a multi-dimensional array into a 1D array.

In [1]:
import numpy as np

# =====================================================================
# 1. ARRAY CREATION
# =====================================================================

# --- np.array() ---
# Convert Python lists or tuples into NumPy ndarrays
list_1d = [1, 2, 3, 4]
arr_1d = np.array(list_1d)

nested_list = [[1, 2, 3], [4, 5, 6]]
arr_2d = np.array(nested_list)

print("np.array (1D):", arr_1d)
print("np.array (2D):\n", arr_2d)


# --- np.zeros() & np.ones() ---
# Generate arrays filled with 0s or 1s of a specified shape tuple: (rows, cols)
zeros_arr = np.zeros((2, 3))        # 2 rows, 3 columns of zeros (float by default)
ones_arr = np.ones((3, 2), dtype=int) # 3 rows, 2 columns of ones (specified integer type)

print("\nnp.zeros((2, 3)):\n", zeros_arr)
print("np.ones((3, 2)):\n", ones_arr)


# --- np.arange(start, stop, step) ---
# Generates values from start up to (excluding) stop with a fixed step size
range_arr = np.arange(0, 10, 2)     # [0, 2, 4, 6, 8]
print("\nnp.arange(0, 10, 2):", range_arr)


# --- np.linspace(start, stop, num) ---
# Generates 'num' evenly spaced values across a closed interval [start, stop]
linear_arr = np.linspace(0, 1, 5)   # 5 points between 0.0 and 1.0
print("np.linspace(0, 1, 5):", linear_arr)


# =====================================================================
# 2. SHAPE & MANIPULATION
# =====================================================================

# --- array.reshape() ---
# Changes the shape of an array without modifying its data (total element count must match)
orig_arr = np.arange(1, 7)          # [1, 2, 3, 4, 5, 6] (6 elements)
reshaped_2d = orig_arr.reshape(2, 3) # 2 rows, 3 columns

print("\nOriginal 1D array:", orig_arr)
print("Reshaped (2, 3):\n", reshaped_2d)


# --- np.concatenate(), np.vstack(), np.hstack() ---
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# np.concatenate: joins along specified axis (default axis=0 -> rows)
concat_axis0 = np.concatenate((a, b), axis=0) # Stacks vertically
concat_axis1 = np.concatenate((a, b), axis=1) # Stacks horizontally

# np.vstack: vertical stack (row-wise)
# np.hstack: horizontal stack (column-wise)
v_stacked = np.vstack((a, b))
h_stacked = np.hstack((a, b))

print("\nnp.vstack / concat axis=0:\n", v_stacked)
print("np.hstack / concat axis=1:\n", h_stacked)


# --- array.flatten() vs. array.ravel() ---
matrix = np.array([[10, 20], [30, 40]])

# .flatten() always creates a NEW deep copy of the data
flat_copy = matrix.flatten()

# .ravel() creates a 1D VIEW (no copy made unless necessary)
flat_view = matrix.ravel()

# Modifying the view affects the original matrix
flat_view[0] = 99

print("\nOriginal matrix after modifying flat_view[0]:\n", matrix)
print(".flatten() (independent copy):", flat_copy)
print(".ravel() (view of matrix):", flat_view)

np.array (1D): [1 2 3 4]
np.array (2D):
 [[1 2 3]
 [4 5 6]]

np.zeros((2, 3)):
 [[0. 0. 0.]
 [0. 0. 0.]]
np.ones((3, 2)):
 [[1 1]
 [1 1]
 [1 1]]

np.arange(0, 10, 2): [0 2 4 6 8]
np.linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]

Original 1D array: [1 2 3 4 5 6]
Reshaped (2, 3):
 [[1 2 3]
 [4 5 6]]

np.vstack / concat axis=0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
np.hstack / concat axis=1:
 [[1 2 5 6]
 [3 4 7 8]]

Original matrix after modifying flat_view[0]:
 [[99 20]
 [30 40]]
.flatten() (independent copy): [10 20 30 40]
.ravel() (view of matrix): [99 20 30 40]


Matplotlib (Data Visualization)
Matplotlib renders static, animated, and interactive visualizations using a object-oriented or state-based API.

Key Concepts

Figure vs. Axes: The Figure acts as the overall canvas; Axes represents individual plot region(s).

Matplotlib (matplotlib.pyplot as plt)
Plot Creation
plt.subplots(nrows, ncols): Creates a figure and a grid of subplot axes (recommended Object-Oriented approach).
plt.plot(): Draws 2D line plots.plt.scatter(): Renders a scatter plot of $x$ vs. $y$.
plt.bar(), plt.barh(): Draws vertical or horizontal bar charts.
plt.hist(): Computes and plots a histogram distribution.
plt.imshow(): Displays image data or 2D numerical matrices as a heatmap.

Customization & Layout
plt.xlabel(), plt.ylabel(), plt.title(): Sets axis labels and main title.
plt.legend(): Places a legend on the axes.
plt.xlim(), plt.ylim(): Gets or sets the $x$ and $y$ limits of the current axes.
plt.grid(): Toggles gridlines.
plt.tight_layout(): Automatically adjusts padding between subplots to prevent overlapping.

Output
plt.show(): Displays all open figures.
plt.savefig(): Saves the current figure to a file (e.g., PNG, PDF, SVG).

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Generate reproducible dummy data
np.random.seed(42)
x = np.linspace(0, 10, 100)
y_line = np.sin(x)
x_scatter = np.random.uniform(0, 10, 30)
y_scatter = np.sin(x_scatter) + np.random.normal(0, 0.2, 30)

categories = ['A', 'B', 'C', 'D']
values = [15, 28, 12, 35]
hist_data = np.random.normal(loc=0, scale=1, size=500)
heatmap_matrix = np.random.rand(8, 8)

# =====================================================================
# 1. PLOT CREATION & CUSTOMIZATION (OBJECT-ORIENTED APPROACH)
# =====================================================================

# --- plt.subplots(nrows, ncols) ---
# Creates a 2x3 grid of subplot axes on a single figure canvas
fig, axes = plt.subplots(nrows=2, ncols=3, figsize=(14, 8))


# --- plt.plot() ---
# 2D line plot (axes[0, 0])
axes[0, 0].plot(x, y_line, color='blue', linewidth=2, label='Sine Wave')
axes[0, 0].set_title('1. Line Plot (plt.plot)')


# --- plt.scatter() ---
# Scatter plot of x vs y (axes[0, 1])
axes[0, 1].scatter(x_scatter, y_scatter, color='red', alpha=0.7, label='Data Points')
axes[0, 1].set_title('2. Scatter Plot (plt.scatter)')


# --- plt.bar() & plt.barh() ---
# Vertical bar chart (axes[0, 2]) and Horizontal bar chart (axes[1, 0])
axes[0, 2].bar(categories, values, color='skyblue')
axes[0, 2].set_title('3. Vertical Bar (plt.bar)')

axes[1, 0].barh(categories, values, color='teal')
axes[1, 0].set_title('4. Horizontal Bar (plt.barh)')


# --- plt.hist() ---
# Histogram distribution (axes[1, 1])
axes[1, 1].hist(hist_data, bins=20, color='purple', edgecolor='black', alpha=0.7)
axes[1, 1].set_title('5. Histogram (plt.hist)')


# --- plt.imshow() ---
# Displays a 2D matrix as a colored heatmap (axes[1, 2])
cax = axes[1, 2].imshow(heatmap_matrix, cmap='viridis')
fig.colorbar(cax, ax=axes[1, 2])  # Add color scale legend
axes[1, 2].set_title('6. Heatmap (plt.imshow)')


# =====================================================================
# 2. CUSTOMIZATION & LAYOUT
# =====================================================================

# Demonstrate customization functions on the first subplot (Line Plot)
# --- plt.xlabel(), plt.ylabel(), plt.title() ---
axes[0, 0].set_xlabel('Time (s)')
axes[0, 0].set_ylabel('Amplitude')

# --- plt.legend() ---
axes[0, 0].legend(loc='upper right')

# --- plt.xlim(), plt.ylim() ---
axes[0, 0].set_xlim(0, 10)
axes[0, 0].set_ylim(-1.5, 1.5)

# --- plt.grid() ---
axes[0, 0].grid(True, linestyle='--', alpha=0.6)


# Apply grid formatting to scatter plot as well
axes[0, 1].grid(True)
axes[0, 1].legend()

# --- plt.tight_layout() ---
# Automatically adjusts padding between subplots to prevent overlapping labels
plt.tight_layout()


# =====================================================================
# 3. OUTPUT
# =====================================================================

# --- plt.savefig() ---
# Saves the current figure canvas to a file on disk
plt.savefig('matplotlib_demo.png', dpi=300, bbox_inches='tight')

# --- plt.show() ---
# Renders the figure window on the screen
plt.show()

Scikit-Learn (Machine Learning)
Scikit-Learn implements standard ML algorithms following a consistent Estimator API (fit, predict, transform).

Key Concepts

Preprocessing & Splits: Scaling features and partitioning datasets into training and testing sets.

Supervised Learning Workflow: Training on labeled data (X_train, y_train) and predicting on held-out samples (X_test).

Scikit-Learn
Data Preparation & Selection (sklearn.model_selection, sklearn.preprocessing)

train_test_split(): Randomly splits arrays or matrices into random train and test subsets.

StandardScaler(), MinMaxScaler(): Standardizes features by removing the mean and scaling to unit variance (or bounded range).

OneHotEncoder(), LabelEncoder(): Encodes categorical features as a one-hot numeric array or integers.

GridSearchCV(), RandomizedSearchCV(): Exhaustive or randomized search over specified parameter values for an estimator.

Estimator Methods (Common API across Models)

.fit(X, y): Trains/fits the model to the training dataset.

.predict(X): Predicts target values or classes for new samples.

.predict_proba(X): Predicts class probabilities (for classification models).

.transform(X) / .fit_transform(X): Transforms input features (used in scalers, encoders, and dimensionality reduction like PCA).

Evaluation Metrics (sklearn.metrics)

accuracy_score(), classification_report(), confusion_matrix(): Evaluates classification performance.

mean_squared_error(), r2_score(), mean_absolute_error(): Measures regression model fit quality.

In [ ]:
import numpy as np
import pandas as pd

# Modules for Data Preparation & Selection
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV
from sklearn.preprocessing import StandardScaler, MinMaxScaler, OneHotEncoder, LabelEncoder

# Estimators for Machine Learning
from sklearn.linear_model import LogisticRegression, Ridge
from sklearn.ensemble import RandomForestClassifier

# Evaluation Metrics
from sklearn.metrics import (
    accuracy_score, classification_report, confusion_matrix,
    mean_squared_error, r2_score, mean_absolute_error
)

# Set random seed for reproducibility
np.random.seed(42)

# =====================================================================
# 1. DATA PREPARATION & SELECTION
# =====================================================================

# Dummy categorical data
cities = np.array(['Manila', 'Cebu', 'Davao', 'Cebu', 'Manila']).reshape(-1, 1)
targets = np.array(['low', 'high', 'medium', 'high', 'low'])

# --- LabelEncoder() ---
# Encodes target labels into 0, 1, 2...
label_enc = LabelEncoder()
y_encoded = label_enc.fit_transform(targets)
print("LabelEncoder Output:", y_encoded)

# --- OneHotEncoder() ---
# Encodes categorical features into binary indicator columns
ohe = OneHotEncoder(sparse_output=False)
cities_ohe = ohe.fit_transform(cities)
print("OneHotEncoder Output:\n", cities_ohe)


# Synthetic Classification Dataset
X_raw = np.random.normal(loc=10, scale=5, size=(100, 2))
y_cls = np.random.choice([0, 1], size=100)

# --- train_test_split() ---
# Splits matrices into random train and test subsets
X_train, X_test, y_train, y_test = train_test_split(
    X_raw, y_cls, test_size=0.2, random_state=42
)

# --- StandardScaler() & MinMaxScaler() ---
# Feature scaling via .fit(), .transform(), or combined .fit_transform()
std_scaler = StandardScaler()
minmax_scaler = MinMaxScaler()

# Fit on train, transform on both
X_train_std = std_scaler.fit_transform(X_train)
X_test_std = std_scaler.transform(X_test)

X_train_minmax = minmax_scaler.fit_transform(X_train)
X_test_minmax = minmax_scaler.transform(X_test)

print("\nStandardScaler Mean (approx 0):", X_train_std.mean(axis=0))
print("MinMaxScaler Min/Max [0, 1]:", X_train_minmax.min(axis=0), X_train_minmax.max(axis=0))


# --- GridSearchCV() & RandomizedSearchCV() ---
# Hyperparameter optimization over estimators
param_grid = {'C': [0.1, 1.0, 10.0]}
grid_search = GridSearchCV(
    estimator=LogisticRegression(),
    param_grid=param_grid,
    cv=3
)
grid_search.fit(X_train_std, y_train)
print("\nGridSearchCV Best Parameter:", grid_search.best_params_)

param_distributions = {'n_estimators': [10, 50, 100], 'max_depth': [2, 5, 10]}
rand_search = RandomizedSearchCV(
    estimator=RandomForestClassifier(random_state=42),
    param_distributions=param_distributions,
    n_iter=3,
    cv=3,
    random_state=42
)
rand_search.fit(X_train_std, y_train)
print("RandomizedSearchCV Best Parameter:", rand_search.best_params_)


# =====================================================================
# 2. ESTIMATOR METHODS & CLASSIFICATION METRICS
# =====================================================================

# Initialize and train model using best estimator from GridSearch
clf_model = grid_search.best_estimator_

# --- .fit(X, y) ---
clf_model.fit(X_train_std, y_train)

# --- .predict(X) ---
y_pred_cls = clf_model.predict(X_test_std)

# --- .predict_proba(X) ---
y_probs = clf_model.predict_proba(X_test_std)

print("\n--- Classification Results ---")
print("First 3 Class Predictions:", y_pred_cls[:3])
print("First 3 Class Probabilities [P(0), P(1)]:\n", y_probs[:3])

# --- Evaluation Metrics (Classification) ---
acc = accuracy_score(y_test, y_pred_cls)
cm = confusion_matrix(y_test, y_pred_cls)
clf_rep = classification_report(y_test, y_pred_cls)

print("\nAccuracy Score:", acc)
print("Confusion Matrix:\n", cm)
print("Classification Report:\n", clf_rep)


# =====================================================================
# 3. REGRESSION METRICS
# =====================================================================

# Synthetic Regression Dataset
X_reg = np.random.uniform(0, 10, (100, 1))
y_reg = 2.5 * X_reg.squeeze() + np.random.normal(0, 1, 100)

X_tr_reg, X_te_reg, y_tr_reg, y_te_reg = train_test_split(X_reg, y_reg, test_size=0.2, random_state=42)

reg_model = Ridge()
reg_model.fit(X_tr_reg, y_tr_reg)
y_pred_reg = reg_model.predict(X_te_reg)

# --- Evaluation Metrics (Regression) ---
mse = mean_squared_error(y_te_reg, y_pred_reg)
mae = mean_absolute_error(y_te_reg, y_pred_reg)
r2 = r2_score(y_te_reg, y_pred_reg)

print("--- Regression Results ---")
print(f"Mean Squared Error (MSE): {mse:.4f}")
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"R² Score:                  {r2:.4f}")